/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tutorial.demo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void https://www.youtube.com/watch?v=dQw4w9WgXcQ() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
